"""Common stages and base classes for launch workflow.

Provides reusable base classes for implementing launch pipeline stages,
including file generation with dry-run support and configuration validation.
"""

from pathlib import Path
from typing import Generic, TypeVar

from slipp import output
from slipp.constants import VALID_PROXIES
from slipp.models.local_config import ExposeEntry
from slipp.models.service import Runtime
from slipp.scanner.routing import default_expose
from slipp.services.launch.context import (
    BaseContext,
    DockerfileContext,
    FullContext,
    ScanContext,
)
from slipp.utils.errors import LaunchError

CtxT = TypeVar("CtxT", bound=BaseContext)
T = TypeVar("T")

GENERATED_MARKER = "# Generated by slipp"


def require(value: T | None, what: str) -> T:
    """Assert a pipeline invariant, raising LaunchError instead of AssertionError.

    Use for values a prior stage is expected to have set on the context --
    unlike `assert`, this isn't stripped under `python -O`, so a broken
    pipeline invariant always surfaces as a clear error instead of a
    None-deref/AttributeError further down the pipeline.

    Args:
        value: Value expected to already be set (non-None).
        what: Human description of the missing value, used in the error.

    Returns:
        value, narrowed to non-None.

    Raises:
        LaunchError: If value is None.
    """
    if value is None:
        raise LaunchError(f"Internal pipeline error: {what} not set by a prior stage")
    return value


def resolve_expose(context: FullContext, domain: str) -> dict[str, ExposeEntry]:
    """Resolve the routing block once per launch, memoized on the context.

    An existing expose: block in slipp.yaml wins (the user's explicit
    routing); otherwise the default convention is seeded from the scanned
    services. Both proxy stages (Caddy, wg-manage) resolve through here so
    they can never route differently, and RegistrationStage persists the
    result back to slipp.yaml.
    """
    if context.expose is None:
        # Lazy: services.config.local imports other launch-adjacent modules.
        from slipp.services.config import LocalConfigService

        existing = LocalConfigService.load(context.output_dir)
        if existing and existing.expose:
            # A seeded block is indistinguishable from a hand-edited one,
            # so a changed app_domain silently keeps the old routing --
            # surface that instead of guessing which the user meant.
            domains = {e.domain for e in existing.expose.values()}
            if not any(d == domain or d.endswith(f".{domain}") for d in domains):
                output.warning(
                    f"slipp.yaml expose: block doesn't reference {domain} "
                    f"(routes: {', '.join(sorted(domains))})"
                )
                output.hint(
                    "Edit expose: to the new domain, or delete the block to re-seed"
                )
            # Coverage drift: a service added after the block was persisted
            # gets no route anywhere. A hint (not a warning) because
            # deleting an entry is also the legitimate way to unexpose a
            # service -- "forgot" and "opted out" look identical from here.
            unexposed = [
                s.name for s in context.services if s.name not in existing.expose
            ]
            if unexposed:
                output.hint(
                    f"Detected but not in the expose: block (unrouted): "
                    f"{', '.join(unexposed)} -- add entries to expose them"
                )
            context.expose = existing.expose
        else:
            context.expose = default_expose(context.services, domain)
    return context.expose


def is_customized(path: Path) -> bool:
    """Return True if an existing generated file has been hand-edited.

    A file is considered customized if it exists and no longer carries the
    slipp generation marker.

    Args:
        path: Path to the file to check.

    Returns:
        True if the file exists and lacks the generation marker.
    """
    if not path.exists():
        return False

    return GENERATED_MARKER not in path.read_text()


def write_generated_file(
    path: Path,
    content: str,
    context: BaseContext,
    *,
    respect_customized: bool = False,
    never_overwrite: bool = False,
) -> None:
    """Write a generated file, handling dry-run, customization, and bookkeeping.

    Shared by every stage that writes slipp-generated files: creates parent
    directories, skips files the user has hand-edited (when
    respect_customized is set) or that must never be overwritten once
    created (when never_overwrite is set), and tracks written paths on the
    context.

    Args:
        path: Destination file path.
        content: File content to write.
        context: Stage execution context with output_dir, dry_run,
            generated_files.
        respect_customized: Skip (with a warning) if the file exists and no
            longer carries the slipp generation marker.
        never_overwrite: Skip (with an info message) if the file already
            exists, regardless of the generation marker. For scaffold
            inventory files (hosts, vars.yml, vault.yml), which carry no
            marker and may hold real secrets from a prior run.
    """
    display_path = str(path.relative_to(context.output_dir))

    if context.dry_run:
        output.hint(f"  Would create: {display_path}")
        return

    if never_overwrite and path.exists():
        output.info(f"Already exists, not overwriting: {display_path}")
        return

    if respect_customized and is_customized(path):
        output.warning(f"  {path} has been customized (skipping)")
        output.hint("     To regenerate: restore slipp marker or delete file")
        return

    path.parent.mkdir(parents=True, exist_ok=True)
    is_new_file = not path.exists()
    path.write_text(content)
    icon = output.ICON_CHECK if is_new_file else output.ICON_REFRESH
    output.list_items([display_path], bullet=icon)
    context.generated_files.append(path)


class FileGenerationStage(Generic[CtxT]):
    """Base class for stages that generate files."""

    def __init__(self, description: str, *, respect_customized: bool = True):
        self.description = description
        self.respect_customized = respect_customized

    def generate_content(self, context: CtxT) -> dict[Path, str]:
        """Generate file content for this stage.

        Args:
            context: Stage execution context containing configuration.

        Returns:
            Dictionary mapping file paths to their content strings.

        Raises:
            NotImplementedError: Must be implemented by subclasses.
        """
        raise NotImplementedError("Subclasses must implement generate_content()")

    def execute(self, context: CtxT) -> None:
        """Execute file generation stage.

        Generates files from context, creates parent directories,
        and logs output. Supports dry-run mode for preview.

        Args:
            context: Stage execution context with output_dir, dry_run flags.
        """
        output.info(f"{self.description}...")

        try:
            files = self.generate_content(context)

            for file_path, content in files.items():
                write_generated_file(
                    file_path,
                    content,
                    context,
                    respect_customized=self.respect_customized,
                )

        except Exception as e:
            raise LaunchError(f"Failed to {self.description.lower()}: {e}") from e


class ValidationStage:
    """Validate proxy choice and runtime."""

    def execute(self, context: ScanContext) -> None:
        """Validate proxy and runtime configuration.

        Checks that proxy choice is in VALID_PROXIES list. Does *not*
        resolve "auto" or set skip_caddy -- that's ProxyResolutionStage's
        job, and it needs inventory (SSH details) that doesn't exist yet
        when this stage runs. Also validates container_runtime when the
        context is a DockerfileContext (contexts with a loaded inventory
        get their runtime from there instead).

        Args:
            context: Stage execution context with proxy setting.

        Raises:
            LaunchError: If proxy or runtime choice is invalid.
        """
        if context.proxy not in VALID_PROXIES:
            raise LaunchError(
                f"Invalid proxy: {context.proxy}\n"
                f"Valid options: {', '.join(VALID_PROXIES)}"
            )

        # Only DockerfileContext carries this field, and it's inherently
        # container-only (no Dockerfile to generate for a systemd deploy) --
        # so this deliberately doesn't accept the full Runtime enum.
        if isinstance(context, DockerfileContext):
            valid_runtimes = [Runtime.DOCKER.value, Runtime.PODMAN.value]
            if context.container_runtime not in valid_runtimes:
                raise LaunchError(
                    f"Invalid container runtime: {context.container_runtime}\n"
                    f"Valid options: {', '.join(valid_runtimes)}"
                )
