"""Common stages and base classes for launch workflow.

Provides reusable base classes for implementing launch pipeline stages,
including file generation with dry-run support and configuration validation.
"""

from pathlib import Path
from typing import Generic, TypeVar

from slipp import output
from slipp.constants import VALID_PROXIES
from slipp.models.service import Runtime
from slipp.services.launch.context import (
    BaseContext,
    DockerfileContext,
    FullContext,
    ScanContext,
)
from slipp.utils.errors import LaunchError

CtxT = TypeVar("CtxT", bound=BaseContext)
T = TypeVar("T")

GENERATED_MARKER = "# Generated by slipp"


def require(value: T | None, what: str) -> T:
    """Assert a pipeline invariant, raising LaunchError instead of AssertionError.

    Use for values a prior stage is expected to have set on the context --
    unlike `assert`, this isn't stripped under `python -O`, so a broken
    pipeline invariant always surfaces as a clear error instead of a
    None-deref/AttributeError further down the pipeline.

    Args:
        value: Value expected to already be set (non-None).
        what: Human description of the missing value, used in the error.

    Returns:
        value, narrowed to non-None.

    Raises:
        LaunchError: If value is None.
    """
    if value is None:
        raise LaunchError(f"Internal pipeline error: {what} not set by a prior stage")
    return value


def is_customized(path: Path) -> bool:
    """Return True if an existing generated file has been hand-edited.

    A file is considered customized if it exists and no longer carries the
    slipp generation marker.

    Args:
        path: Path to the file to check.

    Returns:
        True if the file exists and lacks the generation marker.
    """
    if not path.exists():
        return False

    return GENERATED_MARKER not in path.read_text()


def write_generated_file(
    path: Path,
    content: str,
    context: BaseContext,
    *,
    respect_customized: bool = False,
    never_overwrite: bool = False,
) -> None:
    """Write a generated file, handling dry-run, customization, and bookkeeping.

    Shared by every stage that writes slipp-generated files: creates parent
    directories, skips files the user has hand-edited (when
    respect_customized is set) or that must never be overwritten once
    created (when never_overwrite is set), and tracks written paths on the
    context.

    Args:
        path: Destination file path.
        content: File content to write.
        context: Stage execution context with output_dir, dry_run,
            generated_files.
        respect_customized: Skip (with a warning) if the file exists and no
            longer carries the slipp generation marker.
        never_overwrite: Skip (with an info message) if the file already
            exists, regardless of the generation marker. For scaffold
            inventory files (hosts, vars.yml, vault.yml), which carry no
            marker and may hold real secrets from a prior run.
    """
    display_path = str(path.relative_to(context.output_dir))

    if context.dry_run:
        output.hint(f"  Would create: {display_path}")
        return

    if never_overwrite and path.exists():
        output.info(f"Already exists, not overwriting: {display_path}")
        return

    if respect_customized and is_customized(path):
        output.warning(f"  {path} has been customized (skipping)")
        output.hint("     To regenerate: restore slipp marker or delete file")
        return

    path.parent.mkdir(parents=True, exist_ok=True)
    is_new_file = not path.exists()
    path.write_text(content)
    icon = output.ICON_CHECK if is_new_file else output.ICON_REFRESH
    output.list_items([display_path], bullet=icon)
    context.generated_files.append(path)


class FileGenerationStage(Generic[CtxT]):
    """Base class for stages that generate files."""

    def __init__(self, description: str, *, respect_customized: bool = True):
        self.description = description
        self.respect_customized = respect_customized

    def generate_content(self, context: CtxT) -> dict[Path, str]:
        """Generate file content for this stage.

        Args:
            context: Stage execution context containing configuration.

        Returns:
            Dictionary mapping file paths to their content strings.

        Raises:
            NotImplementedError: Must be implemented by subclasses.
        """
        raise NotImplementedError("Subclasses must implement generate_content()")

    def execute(self, context: CtxT) -> None:
        """Execute file generation stage.

        Generates files from context, creates parent directories,
        and logs output. Supports dry-run mode for preview.

        Args:
            context: Stage execution context with output_dir, dry_run flags.
        """
        output.info(f"{self.description}...")

        try:
            files = self.generate_content(context)

            for file_path, content in files.items():
                write_generated_file(
                    file_path,
                    content,
                    context,
                    respect_customized=self.respect_customized,
                )

        except Exception as e:
            raise LaunchError(f"Failed to {self.description.lower()}: {e}") from e


class ValidationStage:
    """Validate proxy choice, runtime, and set skip_caddy flag."""

    def execute(self, context: ScanContext) -> None:
        """Validate proxy and runtime configuration.

        Checks that proxy choice is in VALID_PROXIES list and sets
        skip_caddy flag to True unless proxy is "caddy" (i.e. also for
        "wg-manage", which uses its own exposure role instead). Also validates
        container_runtime when the context is a DockerfileContext
        (contexts with a loaded inventory get their runtime from there
        instead).

        Args:
            context: Stage execution context with proxy setting.

        Raises:
            LaunchError: If proxy or runtime choice is invalid.
        """
        if context.proxy not in VALID_PROXIES:
            raise LaunchError(
                f"Invalid proxy: {context.proxy}\n"
                f"Valid options: {', '.join(VALID_PROXIES)}"
            )

        context.skip_caddy = context.proxy != "caddy"

        # Only FullContext carries this field (Dockerfile-only generation
        # has no proxy concerns at all).
        if (
            isinstance(context, FullContext)
            and context.public
            and context.proxy != "wg-manage"
        ):
            raise LaunchError("--public only applies to --proxy wg-manage")

        # Only DockerfileContext carries this field, and it's inherently
        # container-only (no Dockerfile to generate for a systemd deploy) --
        # so this deliberately doesn't accept the full Runtime enum.
        if isinstance(context, DockerfileContext):
            valid_runtimes = [Runtime.DOCKER.value, Runtime.PODMAN.value]
            if context.container_runtime not in valid_runtimes:
                raise LaunchError(
                    f"Invalid container runtime: {context.container_runtime}\n"
                    f"Valid options: {', '.join(valid_runtimes)}"
                )
