"""Ansible Galaxy requirements.yml generation stage."""

from pathlib import Path
from typing import Any

from slipp import output
from slipp.generator.requirements_generator import RequirementsGenerator
from slipp.services.launch.stages.common import FileGenerationStage

REQUIREMENTS_MARKER = "# Generated by slipp launch"


class RequirementsFileStage(FileGenerationStage):
    """Generate requirements.yml listing the Galaxy collections the project needs."""

    def __init__(self, requirements_generator: RequirementsGenerator):
        """Initialize with requirements generator.

        Args:
            requirements_generator: Generator for requirements.yml content.
        """
        super().__init__("Generating Galaxy requirements")
        self.generator = requirements_generator

    def generate_content(self, context: Any) -> dict[Path, str]:
        """Generate requirements.yml content, unless it's been hand-customized.

        Skips regeneration if requirements.yml exists and no longer carries the
        slipp generation marker, matching DockerfileGenerationStage's
        customization-preservation behavior.

        Args:
            context: Deployment context with inventory config.

        Returns:
            Dictionary mapping file path to content, or empty if skipped.
        """
        assert context.inventory_config is not None, "Inventory config must be loaded"

        requirements_path = context.output_dir / "requirements.yml"
        if requirements_path.exists():
            existing = requirements_path.read_text()
            if REQUIREMENTS_MARKER not in existing:
                output.warning("requirements.yml has been customized (skipping)")
                output.hint("  To regenerate: restore slipp marker or delete file")
                return {}

        first_host = list(context.inventory_config.hosts.values())[0]
        content = self.generator.generate(first_host.runtime)

        return {requirements_path: content}
