"""Template generator orchestrator.

Ties together fetcher, renderer, and extractors to generate deployment files.
"""

import re
from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse

from slipp import __version__
from slipp.generator.errors import TemplateParseError
from slipp.generator.extractors import extract_template_variables
from slipp.generator.fetcher import TemplateFetcher
from slipp.generator.renderer import render_go_template
from slipp.models.deployment import DetectedService
from slipp.models.service import Runtime


class TemplateGenerator:
    """High-level template generator API.

    Orchestrates template fetching, variable extraction, and rendering.
    """

    def __init__(self):
        """Initialize generator."""
        self.fetcher = TemplateFetcher()

    def generate(
        self,
        service: DetectedService,
        output_dir: Path,
        container_runtime: Runtime = Runtime.DOCKER,
    ) -> dict[Path, str]:
        """Generate the Dockerfile for a detected service.

        Args:
            service: Detected service from scanner
            output_dir: Directory to write generated files
            container_runtime: Container runtime (docker or podman)

        Returns:
            Dictionary mapping the generated Dockerfile's path to its content.
        """
        template_path = self._extract_template_path(service.template_url)
        template = self.fetcher.fetch_template(template_path)
        variables = extract_template_variables(service)
        rendered_content = render_go_template(
            template.content, variables, label=template_path
        )

        if container_runtime == Runtime.PODMAN:
            rendered_content = self._apply_podman_fixes(rendered_content)

        rendered_content = self._fix_copy_dest(rendered_content)

        preamble = self._generate_preamble(template_path)
        final_content = preamble + rendered_content
        output_file = output_dir / template.path

        return {output_file: final_content}

    def _extract_template_path(self, template_url: str) -> str:
        """Extract template path from GitHub raw URL.

        raw.githubusercontent.com URLs always follow the layout
        /<owner>/<repo>/<ref>/<path...>, regardless of branch/ref name.

        Args:
            template_url: GitHub raw URL (from scanner)

        Returns:
            Relative path from repo root

        Raises:
            TemplateParseError: If the URL doesn't have enough path segments
                to contain owner/repo/ref/path

        Example:
            >>> generator = TemplateGenerator()
            >>> url = "https://raw.githubusercontent.com/superfly/flyctl/master/scanner/templates/flask/Dockerfile"
            >>> generator._extract_template_path(url)
            'scanner/templates/flask/Dockerfile'
        """
        segments = urlparse(template_url).path.strip("/").split("/")
        if len(segments) < 4:
            raise TemplateParseError(
                f"Cannot derive template path from URL: {template_url}"
            )
        return "/".join(segments[3:])

    def _generate_preamble(self, template_path: str) -> str:
        """Generate slipp preamble comment block for Dockerfile protection.

        Args:
            template_path: Path to template (e.g., "scanner/templates/flask/Dockerfile")

        Returns:
            Comment block with marker, timestamp, and instructions

        Example:
            # Generated by slipp v0.1.0 on 2025-11-20 01:30:00
            # Template: scanner/templates/flask/Dockerfile
            #
            # To prevent regeneration: Remove this comment block
            #
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        return f"""# Generated by slipp v{__version__} on {timestamp}
# Template: {template_path}
#
# If you've customized this file, slipp will detect the change
# and skip regeneration to preserve your modifications.
# To force regeneration: remove or modify this comment block.

"""

    def _apply_podman_fixes(self, content: str) -> str:
        """Apply Podman compatibility fixes to Dockerfile.

        Fixes Docker-specific features that Podman doesn't support:
        - COPY --link flag (BuildKit optimization)

        Args:
            content: Dockerfile content

        Returns:
            Fixed Dockerfile content compatible with Podman

        Example:
            >>> generator = TemplateGenerator()
            >>> content = "COPY --link package.json ."
            >>> generator._apply_podman_fixes(content)
            'COPY package.json .'
        """
        # Docker BuildKit's --link flag not supported in Podman
        content = content.replace("COPY --link", "COPY")
        return content

    # Bare "." (no trailing slash) as a COPY destination is only valid
    # Dockerfile syntax when there's exactly one <src> -- with two or more
    # (e.g. `COPY package.json package-lock.json .`), both Docker and
    # Podman/buildah reject it: "the destination must be a directory and
    # must end with a slash". Confirmed live 2026-07-18: flyctl's own Node
    # template renders exactly this multi-source shape whenever a lock
    # file exists, while its Python template already uses "./" for the
    # equivalent line -- an inconsistency in the upstream template, not
    # something intentional to preserve. "./" is valid for single-source
    # COPY too, so this runs unconditionally rather than only when
    # multi-source is detected.
    _COPY_DEST_RE = re.compile(r"^(COPY\b.*)\s\.$", re.MULTILINE)

    def _fix_copy_dest(self, content: str) -> str:
        """Rewrite every `COPY ... .` instruction's dest to `./`.

        Args:
            content: Dockerfile content (after any podman fixes)

        Returns:
            Content with COPY destinations normalized to end in "/"

        Example:
            >>> generator = TemplateGenerator()
            >>> content = "COPY --link package.json package-lock.json ."
            >>> generator._fix_copy_dest(content)
            'COPY --link package.json package-lock.json ./'
        """
        return self._COPY_DEST_RE.sub(r"\1 ./", content)
