"""Template generator orchestrator.

Ties together fetcher, renderer, and extractors to generate deployment files.
"""

from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse

from pydantic import BaseModel

from slipp import __version__
from slipp.generator.errors import TemplateFetchError
from slipp.generator.extractors import extract_template_variables
from slipp.generator.fetcher import TemplateFetcher
from slipp.generator.renderer import render_go_template
from slipp.models.deployment import DetectedService


class GeneratedFile(BaseModel):
    """Single generated file."""

    path: Path
    content: str


class TemplateGenerator:
    """High-level template generator API.

    Orchestrates template fetching, variable extraction, and rendering.
    """

    def __init__(self, cache_dir: Path | None = None):
        """Initialize generator with optional cache directory.

        Args:
            cache_dir: Directory to cache templates (default: ~/.cache/slipp/templates)
        """
        self.fetcher = TemplateFetcher(cache_dir)

    def generate(
        self,
        service: DetectedService,
        output_dir: Path,
        force_refresh: bool = False,
        container_runtime: str = "docker",
    ) -> list[GeneratedFile]:
        """Generate deployment files for detected service.

        Args:
            service: Detected service from scanner
            output_dir: Directory to write generated files
            force_refresh: Skip template cache, fetch from GitHub
            container_runtime: Container runtime (docker or podman)

        Returns:
            List of generated files (Dockerfile, .dockerignore, etc.)

        Example:
            >>> from slipp.scanner import scan
            >>> from slipp.generator import TemplateGenerator
            >>> service = scan(Path("examples/PoC"))
            >>> generator = TemplateGenerator()
            >>> files = generator.generate(service, service.path)
            >>> [f.path.name for f in files]
            ['Dockerfile']
        """
        template_path = self._extract_template_path(service.template_url)
        template = self.fetcher.fetch_template(template_path, force_refresh)
        variables = extract_template_variables(service)
        rendered_content = render_go_template(
            template.content, variables, label=template_path
        )

        if container_runtime == "podman":
            rendered_content = self._apply_podman_fixes(rendered_content)

        preamble = self._generate_preamble(template_path)
        final_content = preamble + rendered_content
        output_file = output_dir / template.path

        return [
            GeneratedFile(
                path=output_file,
                content=final_content,
            )
        ]

    def _extract_template_path(self, template_url: str) -> str:
        """Extract template path from GitHub raw URL.

        raw.githubusercontent.com URLs always follow the layout
        /<owner>/<repo>/<ref>/<path...>, regardless of branch/ref name.

        Args:
            template_url: GitHub raw URL (from scanner)

        Returns:
            Relative path from repo root

        Raises:
            TemplateFetchError: If the URL doesn't have enough path segments
                to contain owner/repo/ref/path

        Example:
            >>> generator = TemplateGenerator()
            >>> url = "https://raw.githubusercontent.com/superfly/flyctl/master/scanner/templates/flask/Dockerfile"
            >>> generator._extract_template_path(url)
            'scanner/templates/flask/Dockerfile'
        """
        segments = urlparse(template_url).path.strip("/").split("/")
        if len(segments) < 4:
            raise TemplateFetchError(
                f"Cannot derive template path from URL: {template_url}"
            )
        return "/".join(segments[3:])

    def _generate_preamble(self, template_path: str) -> str:
        """Generate slipp preamble comment block for Dockerfile protection.

        Args:
            template_path: Path to template (e.g., "scanner/templates/flask/Dockerfile")

        Returns:
            Comment block with marker, timestamp, and instructions

        Example:
            # Generated by slipp v0.1.0 on 2025-11-20 01:30:00
            # Template: scanner/templates/flask/Dockerfile
            #
            # To prevent regeneration: Remove this comment block
            #
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        return f"""# Generated by slipp v{__version__} on {timestamp}
# Template: {template_path}
#
# If you've customized this file, slipp will detect the change
# and skip regeneration to preserve your modifications.
# To force regeneration: remove or modify this comment block.

"""

    def _apply_podman_fixes(self, content: str) -> str:
        """Apply Podman compatibility fixes to Dockerfile.

        Fixes Docker-specific features that Podman doesn't support:
        - COPY --link flag (BuildKit optimization)

        Args:
            content: Dockerfile content

        Returns:
            Fixed Dockerfile content compatible with Podman

        Example:
            >>> generator = TemplateGenerator()
            >>> content = "COPY --link package.json ."
            >>> generator._apply_podman_fixes(content)
            'COPY package.json .'
        """
        # Docker BuildKit's --link flag not supported in Podman
        content = content.replace("COPY --link", "COPY")
        return content
