"""Dockerfile generation stage."""

from pathlib import Path
from typing import Any

from slipp import output
from slipp.generator import TemplateGenerator


def _should_regenerate_dockerfile(dockerfile_path: Path) -> bool:
    """Return True if Dockerfile can be regenerated.

    Regenerate only if the file doesn't exist or contains the slipp
    generation marker, indicating it hasn't been customized.

    Args:
        dockerfile_path: Path to the Dockerfile to check.

    Returns:
        True if the file should be regenerated.
    """
    if not dockerfile_path.exists():
        return True

    content = dockerfile_path.read_text()
    marker = "# Generated by slipp"
    return marker in content


class DockerfileGenerationStage:
    """Generate Dockerfiles for all services.

    Generates Dockerfile templates for each service in the configuration
    and writes them to disk, respecting customized files marked by the
    slipp generation marker.

    Attributes:
        generator: TemplateGenerator instance for rendering Dockerfile templates.
    """

    def __init__(self, template_generator: TemplateGenerator):
        self.generator = template_generator

    def execute(self, context: Any) -> None:
        """Generate and write Dockerfiles for all services.

        Iterates through services, generates their Dockerfiles based on
        the first host's container runtime, and writes them to disk unless
        in dry-run mode. Skips overwriting customized files.

        Args:
            context: Launch context containing services, inventory config,
                and generation options.
        """
        output.info("Generating Dockerfiles...")

        assert context.inventory_config is not None, "Inventory config must be loaded"

        first_host = list(context.inventory_config.hosts.values())[0]
        runtime = first_host.container_runtime

        for service in context.services:
            try:
                files = self.generator.generate(
                    service=service,
                    output_dir=service.path,
                    force_refresh=False,
                    container_runtime=runtime,
                )

                for file in files:
                    display_path = (
                        str(file.path.relative_to(context.output_dir))
                        if hasattr(context, "output_dir")
                        else str(file.path)
                    )

                    if context.dry_run:
                        output.hint(f"  Would create: {display_path}")
                    else:
                        if file.path.exists() and not _should_regenerate_dockerfile(
                            file.path
                        ):
                            output.warning(
                                f"  {file.path} has been customized (skipping)"
                            )
                            output.hint(
                                "     To regenerate: restore slipp marker or delete file"
                            )
                            continue

                        is_new_file = not file.path.exists()
                        file.path.write_text(file.content)
                        icon = output.ICON_CHECK if is_new_file else output.ICON_REFRESH
                        output.list_items([display_path], bullet=icon)
                        context.generated_files.append(file.path)

            except Exception as e:
                output.error(f"  Failed to generate {service.name}: {e}")
                continue
